---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jane
  namespace: dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: dev
subjects:
- kind: ServiceAccount
  name: jane
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
