---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ken
  namespace: dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view
  namespace: dev
subjects:
- kind: ServiceAccount
  name: ken
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
